version: "2"

services:

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  mosquitto:
    image: toke/mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"