version: "2"

services:

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  mosquitto:
    image: toke/mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  fluentd:
    image: fluent/fluentd
    container_name: fluent
    volumes:
     - ./logs:/fluentd/log
    ports:
     - "24224:24224"
     
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    environment:
      #- cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - KIBANA_BASE_URL=
    ports:
      - "5601:5601"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
