version: "2"

services:
  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"